Implemented deploy --no-follow flag
Scalingo/cli pull request #679
Opened 2021-09-23 15:46 UTC by stopostit

feat #650

- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

2021-09-23 16:18 UTC, EtienneM reviewed
Just adding some comments about the content of the documentation. Otherwise it looks overall good to me

2021-09-23 16:18 UTC, EtienneM commented on cmd/deployments.go
> +			cli.BoolFlag{Name: "no-follow", Usage: "Disable the display of deployment process if the first API call succeeded"},
I don't think the help message should talk about "API call". Our customers do not know the underlying logic of the `deploy` command, they don't know if there is some API calls or some other magic. What bother them is that when they call this command, it hangs for a long time, then displays the deployment logs, and eventually returns. Whereas there are some situations they want the command to return right after the deployment is triggered. What do you think about this wording:

```suggestion
			cli.BoolFlag{Name: "no-follow", Usage: "Return immediately after the deployment is triggered"},
```

2021-09-23 16:18 UTC, EtienneM commented on cmd/deployments.go
> +			cli.BoolFlag{Name: "no-follow", Usage: "Disable the display of deployment process if the first API call succeeded"},
I would also update the `Description` of this command to add an example with this flag. Something like:

```
$ scalingo --app my-app deploy --no-follow archive.tar.gz v1.0.0
$ scalingo --app my-app deployment-follow
```
The `deployment-follow` call is what you should call if you want to follow the deployment you just triggered.

There is a "See also commands" message in the description and I would add `'deployment-follow'` in it.

2021-09-23 16:18 UTC, EtienneM commented on deployments/deploy.go
> +		scalingoio.Status(fmt.Sprintf("The no-follow flag has been passed. you can check deployment logs with scalingo -a %s deployment-follow", app))
nitpick: 
- replace the use of `Status(fmt.Sprintf(` with `Statusf`
- in informative messages targeted to users, I prefer the use of long options. This is for example the case in our documentation: https://doc.scalingo.com/platform/app/logs
- (i'm not sure about this one.. 😅 ) I think "is passed" is a better conjugation than "has been passed".
- Missing upper case

```suggestion
		scalingoio.Statusf("The no-follow flag is passed. You can check deployment logs with scalingo --app %s deployment-follow", app)
```

2021-09-23 16:59 UTC, EtienneM requested changes
Test

2021-09-23 16:59 UTC, EtienneM reviewed
gregregre

2021-09-23 17:00 UTC, EtienneM approved these changes

2021-09-23 17:00 UTC, EtienneM requested changes
Test

2021-09-24 07:01 UTC, EtienneM approved these changes
Nice! 👍🏾

2021-09-24 07:01 UTC, merged

2021-10-05 08:26 UTC, Intrepidd commented
Thank you so much for implementing this ! I'd love to use it ASAP, would it be possible to release it ? Thanks !

2021-10-07 07:30 UTC, EtienneM commented
> Thank you so much for implementing this ! I'd love to use it ASAP, would it be possible to release it ? Thanks !

Hi @Intrepidd! We plan to release a new version by the end of next week :)

2021-10-15 09:43 UTC, Intrepidd commented
Thanks so much ! On my way to reduce my deploy scripts by 90% 😅