feat(workflows/publish): golangci-lint
Scalingo/cli pull request #758
Opened 2022-08-03 14:12 UTC by EtienneM

Wait for https://github.com/Scalingo/cli/pull/757 to make this reviewable

2024-02-14 09:48 UTC, curzolapierre requested changes
Overall it's LGTM

However I've small questions

Note for later, we could also separate the `linter-pull-request` and `linter-master` jobs by another trigger. Here, we use `on: [push]` for both, we may want to use `on: [pull-request]` in the future to simplify configuration.

2024-02-14 10:02 UTC, EtienneM commented on .github/workflows/publish.yml
> +          args: "--config=$(pwd)/.golangci.yml --new --new-from-rev=HEAD~1"
I actually misunderstood the use of `--new`. I removed the use of `--new` in f6aa960c. Here isthis option documentation:

> Show only new issues: if there are unstaged changes or untracked files, only those changes are analyzed

2024-02-14 10:03 UTC, EtienneM commented on .github/workflows/publish.yml
> +          NEW_FROM_REV: ${{ steps.new-from-rev.outputs.NEW_FROM_REV }}
You are right it's useless. Removed in b57c7fb. Thanks :+1:

2024-02-14 11:16 UTC, curzolapierre approved these changes

2024-02-14 11:16 UTC, merged

2024-02-16 12:49 UTC, EtienneM commented
With this PR being merged, I removed CodeShip from this project.