feat(integration-link): add --follow arg to manual-deploy command
Scalingo/cli pull request #936
Opened 2023-04-16 12:18 UTC by gnuletik

- [x] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

Depends on https://github.com/Scalingo/go-scalingo/pull/332

2023-04-18 14:41 UTC, gnuletik commented
I rebased my fork with `github.com/Scalingo/go-scalingo/v6@v6.5.0` @EtienneM

2023-04-20 09:34 UTC, gnuletik commented
@EtienneM Let me know if anything is blocking this. Thanks!

2023-04-20 11:19 UTC, EtienneM requested changes
Sorry I didn't took the time earlier to review this PR

2023-04-20 11:19 UTC, EtienneM commented on cmd/integration_link.go
> +			&cli.BoolFlag{Name: "follow", Usage: "Follow deployment"},
let's also allow the short version of the flag
+ use the same wording as the `deployment-follow` command

```suggestion
			&cli.BoolFlag{Name: "follow", Aliases: []string{"f"}, Usage: "Follow deployment event stream"},
```

2023-04-20 11:19 UTC, EtienneM commented on integrationlink/manual_deploy.go
> +		return errgo.Mask(err, errgo.Any)
convention: We no longer use `errgo.Mask`
```suggestion
		return errgo.Notef(err, "stream deployment logs")
```

2023-04-20 11:23 UTC, EtienneM approved these changes

2023-04-20 11:33 UTC, merged